-- Migration 019: Add WebRTC Call Support
-- This migration adds tables to support custom WebRTC calls and their lifecycle events.

-- CallSession: Core session data
CREATE TABLE IF NOT EXISTS "CallSession" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "clientId" TEXT NOT NULL,
  "alertId" TEXT,
  "sopResponseId" TEXT,
  status TEXT NOT NULL DEFAULT 'pending', -- pending|ringing|active|ended|failed
  "initiatedBy" TEXT,
  "answeredByDeviceId" TEXT,
  "startedAt" TIMESTAMP,
  "endedAt" TIMESTAMP,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("clientId") REFERENCES "Client"(id) ON DELETE CASCADE,
  FOREIGN KEY ("alertId") REFERENCES "Alert"(id) ON DELETE SET NULL,
  FOREIGN KEY ("sopResponseId") REFERENCES "SOPResponse"(id) ON DELETE SET NULL,
  FOREIGN KEY ("initiatedBy") REFERENCES "User"(id) ON DELETE SET NULL,
  FOREIGN KEY ("answeredByDeviceId") REFERENCES "Device"(id) ON DELETE SET NULL
);

-- CallParticipant: Tracks participants in a call
CREATE TABLE IF NOT EXISTS "CallParticipant" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "callSessionId" TEXT NOT NULL,
  "userId" TEXT,
  "deviceId" TEXT,
  role TEXT NOT NULL, -- staff|tablet|observer
  "joinedAt" TIMESTAMP,
  "leftAt" TIMESTAMP,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("callSessionId") REFERENCES "CallSession"(id) ON DELETE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE SET NULL,
  FOREIGN KEY ("deviceId") REFERENCES "Device"(id) ON DELETE SET NULL
);

-- CallEvent: Audit log for signaling and call lifecycle events
CREATE TABLE IF NOT EXISTS "CallEvent" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "callSessionId" TEXT NOT NULL,
  type TEXT NOT NULL, -- invite|offer|answer|ice|connected|ended|failed|timeout
  payload JSONB,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("callSessionId") REFERENCES "CallSession"(id) ON DELETE CASCADE
);

-- CallRecording: Metadata for stored media and transcript links
CREATE TABLE IF NOT EXISTS "CallRecording" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "callSessionId" TEXT NOT NULL,
  "recordingUrl" TEXT,
  "storagePath" TEXT,
  "transcriptId" TEXT,
  "processingStatus" TEXT DEFAULT 'pending', -- pending|processing|completed|failed
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("callSessionId") REFERENCES "CallSession"(id) ON DELETE CASCADE,
  FOREIGN KEY ("transcriptId") REFERENCES "Transcript"(id) ON DELETE SET NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_callsession_client ON "CallSession"("clientId");
CREATE INDEX IF NOT EXISTS idx_callsession_status ON "CallSession" (status);
CREATE INDEX IF NOT EXISTS idx_callevent_session ON "CallEvent"("callSessionId");
CREATE INDEX IF NOT EXISTS idx_callrecording_session ON "CallRecording"("callSessionId");

-- Add comments
COMMENT ON TABLE "CallSession" IS 'Core session data for custom WebRTC calls';
COMMENT ON TABLE "CallParticipant" IS 'Tracks users and devices participating in a call session';
COMMENT ON TABLE "CallEvent" IS 'Audit log of signaling and connectivity events for a call';
COMMENT ON TABLE "CallRecording" IS 'Meta-data for recordings generated by the custom WebRTC engine';
